// Material IDs (shared by sim.frag, sim.comp, and sim_common.glsl).
const uint M_EMPTY = 0u;
const uint M_SAND  = 1u;
const uint M_WATER = 2u;
const uint M_FIRE  = 3u;
const uint M_SMOKE = 4u;
const uint M_WALL  = 5u;
const uint M_ACID  = 6u;
const uint M_PLANT = 7u;
const uint M_LAVA  = 8u;
const uint M_STONE = 9u;
const uint M_OIL   = 10u;
const uint M_ICE   = 11u;
const uint M_STEAM = 12u;
const uint M_GLASS = 13u;
const uint M_WOOD  = 14u;
const uint M_METAL = 15u;
const uint M_GUNPOWDER = 16u;
const uint M_SALT      = 17u;
const uint M_EMBER     = 18u;
const uint M_FLOWER    = 19u;
const uint M_COAL      = 20u;
const uint M_LEGACY_TNT = 21u; // removed — sim maps to empty
const uint M_BRICK     = 22u;
